import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';

// import App from './compo/Filterable';
// import App from './compo/Ctx/App.js';
// import App from './compo/redu';
// import App from './compo/theme';
// import App from './compo/render';
// import App from './compo/parallax/App';
// import App from './compo/dropdown/App';
// import App from './compo/Ripples';
// import App from './compo/ndrstandStateChnage';
// import App from './compo/nav/App';
// import App from './compo/Stack';
// import App from './compo/query/App';
// import App from './compo/Framer/App';
// import App from './compo/graphql/App';
// import App from './compo/Suspense/App';
// import App from './compo/LazyImg';
// import App from './compo/Lazy/App.js';
// import App from './compo/FireUpload/App';
// import App from './compo/Multi/App';
// import App from './compo/ATM/App';
// import App from './compo/Saga/App.js';
// import App from './compo/Life/App';
// import App from './compo/Ripple/App';
import App from './compo/material';
// import App from './compo/skeleton';

ReactDOM.render(<App />, document.getElementById('root'));
